version: '3.3'
services:
    dpp_db:
        image: mysql:8
        container_name: dpp_mysql_db
        ports:
            - "33360:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: dpp
        volumes:
            - ./data:/var/lib/mysql
        restart: unless-stopped
